org.gradle.caching=true
org.gradle.jvmargs=-Xmx1g
org.gradle.parallel=true
org.gradle.vfs.watch=true

#TODO: arthurosncf
compatibleVersion=SKIP

kotlin.stdlib.default.dependency=false

nebula.dependencyLockPluginEnabled=false

centralUsername="-"
centralPassword="-"

mavenCentralUsername="-"
mavenCentralPassword="-"

release.stage=nebula.plugin.release.git.opinion.Strategies.FINAL
release.version=1.15.0
